# Site settings
title: Dingawm
email: dingawm@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  羁绊。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dingawm.cn" # the base hostname & protocol for your site
github_username:  dingawm

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: 
  option2:
    name: Cool Option 2
    link: 
  option3:
    name: Cool Option 3
    link: 

disqus: true
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
